In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3], dtype="int16")
print(a)

[1 2 3]


In [5]:
b = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [6]:
# Get Dimensions
b.ndim

2

In [7]:
# Get Shape
b.shape

(2, 3)

In [8]:
# Get Type of array
b.dtype

dtype('float64')

In [9]:
# Get size for each element in the array
b.itemsize

8

In [10]:
# Get total elements in the array
b.size

6

In [15]:
# Get total size of a array 
b.size * b.itemsize

48


In [16]:
b.nbytes

48

In [17]:
# Getting a specific element
b[1,2]

6.0

In [18]:
b[0,1]

2.0

In [20]:
a[0]

1

In [21]:
# Get a specific row complete
b[0, :]

array([1., 2., 3.])

In [23]:
# Get a specific column complete
b[:, 1]

array([2., 5.])

In [26]:
# Get a little more fancy [startindex:endindex:stepsize]

b[0, 0:2:1]

array([1., 2.])

In [27]:
b[0,1] = 30

In [28]:
b

array([[ 1., 30.,  3.],
       [ 4.,  5.,  6.]])

In [29]:
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], dtype='int32')

In [30]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)

In [34]:
# Get specific element (outside in)
c[0, 1, 1]

4

In [35]:
c.shape

(2, 2, 2)

In [37]:
# Creating Matrices

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
np.ones((2,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [40]:
np.full((2, 3), 99, dtype='int16')

array([[99, 99, 99],
       [99, 99, 99]], dtype=int16)

In [41]:
np.full_like(b, 5)

array([[5., 5., 5.],
       [5., 5., 5.]])

In [43]:
np.random.rand(2, 3)

array([[0.21746749, 0.96562912, 0.78969601],
       [0.21345004, 0.32650737, 0.56782483]])

In [44]:
np.random.randint(7, size=(3, 3))

array([[4, 6, 5],
       [3, 6, 6],
       [0, 5, 2]])

In [45]:
np.random.randint(-5, 8, size=(3, 3))

array([[ 4, -3,  6],
       [-1, -1, -2],
       [ 5, -2,  5]])

In [46]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [49]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [50]:
# Math capabilities

q = np.array([1,2,2,3,4,5,66])
q

array([ 1,  2,  2,  3,  4,  5, 66])

In [51]:
q+2

array([ 3,  4,  4,  5,  6,  7, 68])

In [52]:
q-2

array([-1,  0,  0,  1,  2,  3, 64])

In [53]:
q*2

array([  2,   4,   4,   6,   8,  10, 132])

In [54]:
q/2

array([ 0.5,  1. ,  1. ,  1.5,  2. ,  2.5, 33. ])

In [55]:
np.tan(q)

array([ 1.55740772, -2.18503986, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501,  0.02656052])

In [59]:
w = np.ones((2,3))
print(w)

e = np.full((3,2), 4)

print(e)

np.matmul(w,e)

[[1. 1. 1.]
 [1. 1. 1.]]
[[4 4]
 [4 4]
 [4 4]]


array([[12., 12.],
       [12., 12.]])

In [60]:
# To find determinant

r = np.identity(3)
np.linalg.det(r)

1.0

In [61]:
stats = np.array([[12, 13, 15], [17, 15, 13]])
stats

array([[12, 13, 15],
       [17, 15, 13]])

In [62]:
np.min(stats)

12

In [66]:
np.max(stats)

17

In [67]:
np.max(stats, axis=1)

array([15, 17])

In [68]:
np.max(stats, axis=0)

array([17, 15, 15])

In [75]:
# Re Organize Array

before = np.array([[12, 13, 15, 77], [17, 15, 13, 99]])
print(before)
after = before.reshape((4, 2, 1))
print(after)

[[12 13 15 77]
 [17 15 13 99]]
[[[12]
  [13]]

 [[15]
  [77]]

 [[17]
  [15]]

 [[13]
  [99]]]


In [77]:
# vstack

v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])